const DYE_COLORS = [
	'white',
	'blue',
	'purple',
	'light_gray',
	'gray',
	'magenta',
	'pink',
	'black',
	'brown',
	'red',
	'orange',
	'yellow',
	'lime',
	'green',
	'cyan',
	'light_blue',
];

const INFESTED_BLOCKS = [
	'sculkhorde:infested_crying_obsidian',
	'sculkhorde:infested_cobblestone',
	'sculkhorde:infested_stone',
	'sculkhorde:infested_andesite',
	'sculkhorde:infested_diorite',
	'sculkhorde:infested_granite',
	'sculkhorde:infested_calcite',
	'sculkhorde:infested_deepslate',
	'sculkhorde:infested_cobbled_deepslate',
	'sculkhorde:infested_tuff',
	'sculkhorde:infested_sandstone',
	'sculkhorde:infested_terracotta',
	'sculkhorde:infested_black_terracotta',
	'sculkhorde:infested_blue_terracotta',
	'sculkhorde:infested_brown_terracotta',
	'sculkhorde:infested_cyan_terracotta',
	'sculkhorde:infested_gray_terracotta',
	'sculkhorde:infested_green_terracotta',
	'sculkhorde:infested_light_blue_terracotta',
	'sculkhorde:infested_light_gray_terracotta',
	'sculkhorde:infested_lime_terracotta',
	'sculkhorde:infested_magenta_terracotta',
	'sculkhorde:infested_orange_terracotta',
	'sculkhorde:infested_pink_terracotta',
	'sculkhorde:infested_purple_terracotta',
	'sculkhorde:infested_red_terracotta',
	'sculkhorde:infested_white_terracotta',
	'sculkhorde:infested_yellow_terracotta',
	'sculkhorde:infested_netherrack',
	'sculkhorde:infested_crimson_nylium',
	'sculkhorde:infested_warped_nylium',
	'sculkhorde:infested_blackstone',
	'sculkhorde:infested_basalt',
	'sculkhorde:infested_smooth_basalt',
	'sculkhorde:infested_endstone',
	'sculkhorde:infested_mossy_cobblestone',
	'sculkhorde:infested_stone_bricks',
	'sculkhorde:infested_mossy_stone_bricks',
	'sculkhorde:infested_blackstone_bricks',
	'sculkhorde:infested_clay',

	'minecraft:sculk',
	'minecraft:sculk_catalyst',
	'minecraft:sculk_vein',
	'sculkhorde:sculk_ancient_node',
	'sculkhorde:sculk_node',
	'sculkhorde:sculk_arachnoid',
	'sculkhorde:sculk_dura_matter',
	'sculkhorde:sculk_living_rock',
	'sculkhorde:sculk_living_rock_root',
	'sculkhorde:calcite_ore',
	'sculkhorde:infested_sand',
	'sculkhorde:infested_snow',
	'sculkhorde:infested_gravel',
	'sculkhorde:infested_red_sand',
	'sculkhorde:infested_mud',
	'sculkhorde:infested_packed_mud',
	'sculkhorde:infested_mud_bricks',
	'sculkhorde:infested_moss',

	'sculkhorde:sculk_bee_nest',
	'sculkhorde:sculk_bee_nest_cell',
	'sculkhorde:bee_colony_core_block',
	'sculkhorde:soulite_core_block',
	'sculkhorde:budding_soulite_block',
	'sculkhorde:soulite_block',
	'sculkhorde:depleted_soulite_block',
	'sculkhorde:fungal_shroom_core_block',
	'sculkhorde:fungal_sculk_block',
	'sculkhorde:fungal_sculk_stem_block',
	'sculkhorde:tendril_core_block',
	'sculkhorde:diseased_kelp_block',
	'sculkhorde:tendrils',

	'sculkhorde:infested_sturdy_mass',
	'sculkhorde:infested_crumpled_mass',
	'sculkhorde:infested_wood_mass',
	'sculkhorde:infested_compost_mass',
	'sculkhorde:infested_log',
	'sculkhorde:infested_wood_stairs',
	'sculkhorde:infested_mossy_cobblestone_stairs',
	'sculkhorde:infested_cobblestone_stairs',
	'sculkhorde:infested_stone_stairs',
	'sculkhorde:infested_sandstone_stairs',
	'sculkhorde:infested_diorite_stairs',
	'sculkhorde:infested_andesite_stairs',
	'sculkhorde:infested_granite_stairs',
	'sculkhorde:infested_cobbled_deepslate_stairs',
	'sculkhorde:infested_blackstone_stairs',
	'sculkhorde:infested_sturdy_stairs',
	'sculkhorde:infested_mud_brick_stairs',
	'sculkhorde:infested_stone_brick_stairs',
	'sculkhorde:infested_mossy_stone_brick_stairs',
	'sculkhorde:infested_blackstone_brick_stairs',

	'sculkhorde:infested_wood_slab',
	'sculkhorde:infested_cobblestone_slab',
	'sculkhorde:infested_stone_slab',
	'sculkhorde:infested_mossy_cobblestone_slab',
	'sculkhorde:infested_andesite_slab',
	'sculkhorde:infested_granite_slab',
	'sculkhorde:infested_diorite_slab',
	'sculkhorde:infested_sandstone_slab',
	'sculkhorde:infested_cobbled_deepslate_slab',
	'sculkhorde:infested_blackstone_slab',
	'sculkhorde:infested_mud_brick_slab',
	'sculkhorde:infested_sturdy_slab',
	'sculkhorde:infested_crumbling_slab',
	'sculkhorde:infested_stone_brick_slab',
	'sculkhorde:infested_mossy_stone_brick_slab',
	'sculkhorde:infested_blackstone_brick_slab',

	'sculkhorde:infested_sandstone_wall',
	'sculkhorde:infested_andesite_wall',
	'sculkhorde:infested_granite_wall',
	'sculkhorde:infested_diorite_wall',
	'sculkhorde:infested_stone_brick_wall',
	'sculkhorde:infested_mossy_stone_brick_wall',
	'sculkhorde:infested_cobblestone_wall',
	'sculkhorde:infested_mossy_cobblestone_wall',
	'sculkhorde:infested_blackstone_wall',
	'sculkhorde:infested_blackstone_brick_wall',
	'sculkhorde:infested_mud_brick_wall',
	'sculkhorde:infested_cobbled_deepslate_wall',
	'sculkhorde:infested_sturdy_wall',
	'sculkhorde:infested_crumbling_wall',

	'sculkhorde:infested_wood_fence',
	'sculkhorde:infested_sturdy_fence',

	'sculkhorde:infested_wood_fence_gate',
	'sculkhorde:infested_sturdy_fence_gate',
];

const SCULK_ENTITIES = [
	'sculkhorde:sculk_mite',
	'sculkhorde:sculk_mite_aggressor',
	'sculkhorde:sculk_bee_harvester',
	'sculkhorde:sculk_bee_infector',
	'sculkhorde:sculk_creeper',
	'sculkhorde:sculk_enderman',
	'sculkhorde:sculk_hatcher',
	'sculkhorde:sculk_ravager',
	'sculkhorde:sculk_spitter',
	'sculkhorde:sculk_spore_spewer',
	'sculkhorde:sculk_vindicator',
	'sculkhorde:sculk_zombie',
	'sculkhorde:sculk_phantom',
	'sculkhorde:sculk_phantom_corpse',
	'sculkhorde:sculk_salmon',
	'sculkhorde:sculk_squid',
	'sculkhorde:sculk_pufferfish',
	'sculkhorde:sculk_witch',
	'sculkhorde:sculk_soul_reaper',
	'sculkhorde:sculk_vex',
	'sculkhorde:living_armor',
	'sculkhorde:sculk_guardian',
	'sculkhorde:sculk_brood_hatcher',
	'sculkhorde:sculk_broodling',
	'sculkhorde:sculk_sheep',
	'sculkhorde:sculk_metamorphosis_pod',
	'sculkhorde:sculk_ghast',
	'sculkhorde:sculk_leech',
	'sculkhorde:sculk_stinger',
];

const $CursorSurfacePurifierEntity = Java.loadClass(
	'com.github.sculkhorde.common.entity.infection.CursorSurfacePurifierEntity'
);
const $MobEffectInstance = Java.loadClass(
	'net.minecraft.world.effect.MobEffectInstance'
);
const $ModMobEffects = Java.loadClass(
	'com.github.sculkhorde.core.ModMobEffects'
);

const $EntityAlgo = Java.loadClass(
	'com.github.sculkhorde.util.EntityAlgorithms'
);

const $SculkHorde = Java.loadClass('com.github.sculkhorde.core.SculkHorde');
const $ModSavedData = Java.loadClass('com.github.sculkhorde.core.ModSavedData');
const $GunItem = Java.loadClass('top.ribs.scguns.item.GunItem');

const WEAPON_TYPES = [
	'greatsword',
	'halberd',
	'hammer',
	'katana',
	'rapier',
	'scythe',
	'warglaive',
	'mace',
	'spear',
];
const WEAPON_MATERIALS = [
	'wooden',
	'stone',
	'iron',
	'golden',
	'diamond',
	'netherite',
    "copper",
];

const RUNIC_ETCHING_COLORS = [
	'rainbow',
	'white',
	'gray',
	'light_gray',
	'black',
	'brown',
	'red',
	'orange',
	'yellow',
	'lime',
	'green',
	'cyan',
	'light_blue',
	'blue',
	'purple',
	'magenta',
	'pink',
];

const NEW_ROUGH_GEMS = ['ruby', 'sapphire', 'cinnabar', 'apatite'];

const AVAILABLE_RELICS = [
	Item.of('relics:amphibian_boot'),
	Item.of('relics:wool_mitten'),
	Item.of('relics:horse_flute'),
	Item.of('relics:leather_belt'),
	Item.of('relics:roller_skates'),
	Item.of('relics:shadow_glaive'),
	Item.of('relics:spore_sack'),
	Item.of('relics:blazing_flask'),
	Item.of('relics:ice_breaker'),
	Item.of('relics:magic_mirror'),
	Item.of('relics:elytra_booster'),
	Item.of('relics:enders_hand'),
	Item.of('relics:holy_locket'),
	Item.of('relics:space_dissector'),
	Item.of('relics:chorus_inhibitor'),
	Item.of('relics:bastion_ring'),
	Item.of('relics:ice_skates'),
	Item.of('relics:rage_glove'),
	Item.of('relics:hunter_belt'),
	Item.of('relics:jellyfish_necklace'),
	Item.of('relics:drowned_belt'),
	Item.of('relics:midnight_robe'),
	Item.of('relics:aqua_walker'),
	Item.of('relics:magma_walker'),
	Item.of('relics:reflection_necklace'),
	Item.of('relics:spatial_sign'),
	Item.of('minecraft:totem_of_undying'),
];

const WEAPON_MAP = {
	'minecraft:wooden_sword': [
		'moonsweaponry:wooden_greatsword',
		'moonsweaponry:wooden_halberd',
		'moonsweaponry:wooden_hammer',
		'moonsweaponry:wooden_katana',
		'moonsweaponry:wooden_rapier',
		'moonsweaponry:wooden_scythe',
		'moonsweaponry:wooden_warglaive',
		'moonsweaponry:wooden_mace',
		'moonsweaponry:wooden_spear',
		'minecraft:wooden_sword',
	],
	'minecraft:stone_sword': [
		'minecraft:stone_sword',
		'moonsweaponry:stone_greatsword',
		'moonsweaponry:stone_halberd',
		'moonsweaponry:stone_hammer',
		'moonsweaponry:stone_katana',
		'moonsweaponry:stone_rapier',
		'moonsweaponry:stone_scythe',
		'moonsweaponry:stone_warglaive',
		'moonsweaponry:stone_mace',
		'moonsweaponry:stone_spear',
	],
	'minecraft:iron_sword': [
		'moonsweaponry:iron_greatsword',
		'moonsweaponry:iron_halberd',
		'moonsweaponry:iron_hammer',
		'moonsweaponry:iron_katana',
		'moonsweaponry:iron_rapier',
		'moonsweaponry:iron_scythe',
		'moonsweaponry:iron_warglaive',
		'moonsweaponry:iron_mace',
		'moonsweaponry:iron_spear',
		'minecraft:iron_sword',
	],
	'minecraft:diamond_sword': [
		'moonsweaponry:diamond_greatsword',
		'moonsweaponry:diamond_halberd',
		'moonsweaponry:diamond_hammer',
		'moonsweaponry:diamond_katana',
		'moonsweaponry:diamond_rapier',
		'moonsweaponry:diamond_scythe',
		'moonsweaponry:diamond_warglaive',
		'moonsweaponry:diamond_mace',
		'moonsweaponry:diamond_spear',
		'minecraft:diamond_sword',
	],
	'caverns_and_chasms:silver_sword': [
		'kubejs:silver_greatsword',
		'kubejs:silver_halberd',
		'kubejs:silver_hammer',
		'kubejs:silver_katana',
		'kubejs:silver_rapier',
		'kubejs:silver_scythe',
		'kubejs:silver_warglaive',
		'kubejs:silver_mace',
		'kubejs:silver_spear',
		'caverns_and_chasms:silver_sword',
	],
};

const DIAMOND_STUFF = [
	'minecraft:diamond_shovel',
	'minecraft:diamond_pickaxe',
	'minecraft:diamond_axe',
	'minecraft:diamond_hoe',
	'minecraft:diamond_sword',
	'minecraft:diamond_helmet',
	'minecraft:diamond_chestplate',
	'minecraft:diamond_leggings',
	'minecraft:diamond_boots',
	'farmersdelight:diamond_knife',
];