
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.thermal]
			rubberwood = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

	[types.cake]

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.cake.farmersrespite]
			coffee_cake = true

	[types.leaves_type]

		[types.leaves_type.environmental]
			hibiscus = true
			willow = true
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.thermal]
			rubberwood = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

	[types.cut_block_type]

		[types.cut_block_type.scguns]
			phosphorite_brick = true
			asgharian_brick = true
			cut_diamond_steel = true
			diamond_steel_tiles = true
			cut_anthralite = true
			anthralite_tiles = true
			cut_treated_iron = true
			cut_treated_brass = true
			treated_brass_tiles = true

		[types.cut_block_type.thermal]
			rubberwood = true

		[types.cut_block_type.sculkhorde]
			infested_stone = true
			infested_sandstone = true
			infested_diorite = true
			infested_granite = true
			infested_andesite = true
			infested_cobbled_deepslate = true
			infested_cobblestone = true
			infested_mud_brick = true
			infested_blackstone = true
			infested_mossy_cobblestone = true
			infested_stone_brick = true
			infested_mossy_stone_brick = true
			infested_blackstone_brick = true

		[types.cut_block_type.environmental]
			dirt_brick = true
			dirt_tile = true
			smooth_mud = true
			grass_thatch = true
			cattail_thatch = true
			duckweed_thatch = true
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.cut_block_type.savage_and_ravage]
			gloomy_tile = true

		[types.cut_block_type.clayworks]
			terracotta = true
			white_terracotta = true
			orange_terracotta = true
			magenta_terracotta = true
			light_blue_terracotta = true
			yellow_terracotta = true
			lime_terracotta = true
			pink_terracotta = true
			gray_terracotta = true
			light_gray_terracotta = true
			cyan_terracotta = true
			purple_terracotta = true
			blue_terracotta = true
			brown_terracotta = true
			green_terracotta = true
			red_terracotta = true
			black_terracotta = true
			terracotta_brick = true
			white_terracotta_brick = true
			orange_terracotta_brick = true
			magenta_terracotta_brick = true
			light_blue_terracotta_brick = true
			yellow_terracotta_brick = true
			lime_terracotta_brick = true
			pink_terracotta_brick = true
			gray_terracotta_brick = true
			light_gray_terracotta_brick = true
			cyan_terracotta_brick = true
			purple_terracotta_brick = true
			blue_terracotta_brick = true
			brown_terracotta_brick = true
			green_terracotta_brick = true
			red_terracotta_brick = true
			black_terracotta_brick = true

		[types.cut_block_type.upgrade_aquatic]
			beachgrass_thatch = true
			luminous_prismarine = true
			tooth_brick = true
			scute_shingle = true
			scute_pavement = true
			coralstone = true
			bubble_coralstone = true
			horn_coralstone = true
			tube_coralstone = true
			brain_coralstone = true
			fire_coralstone = true
			acan_coralstone = true
			finger_coralstone = true
			star_coralstone = true
			moss_coralstone = true
			petal_coralstone = true
			branch_coralstone = true
			rock_coralstone = true
			pillow_coralstone = true
			silk_coralstone = true
			chrome_coralstone = true
			prismarine_coralstone = true
			elder_prismarine_coralstone = true
			dead_coralstone = true
			kelpy_cobblestone = true
			kelpy_stone_brick = true
			kelpy_cobblestone_brick = true
			kelpy_cobblestone_tile = true
			driftwood = true
			river = true

		[types.cut_block_type.neapolitan]
			chocolate_brick = true
			chocolate_tile = true
			frond_thatch = true

		[types.cut_block_type.caverns_and_chasms]
			sanguine_tile = true
			fortified_sanguine_tile = true
			spinel_brick = true
			lapis_brick = true
			cobblestone_brick = true
			mossy_cobblestone_brick = true
			cobblestone_tile = true
			mossy_cobblestone_tile = true
			cobbled_deepslate_brick = true
			cobbled_deepslate_tile = true
			calcite = true
			polished_calcite = true
			tuff = true
			polished_tuff = true
			sugilite = true
			polished_sugilite = true
			dripstone_shingle = true
			cut_amethyst_brick = true
			azalea = true
			turquoise_tile = true
			granite_brick = true
			granite_tile = true
			diorite_brick = true
			diorite_tile = true
			andesite_brick = true
			andesite_tile = true
			calcite_brick = true
			tuff_brick = true
			smooth_tuff = true
			sugilite_brick = true
			smooth_cylindrite = true
			cylindrite_brick = true
			polished_cylindrite = true
			cassiterite = true
			smooth_cassiterite = true
			cassiterite_brick = true
			polished_cassiterite = true
			rhyolite = true
			polished_rhyolite = true
			rhyolite_brick = true
			magmatic_rhyolite = true
			polished_magmatic_rhyolite = true
			magmatic_rhyolite_brick = true
			smooth_dripstone = true
			polished_dripstone = true
			dripstone_brick = true
			iron_brick = true
			tin_brick = true
			gold_brick = true
			silver_brick = true
			copper_brick = true
			exposed_copper_brick = true
			weathered_copper_brick = true
			oxidized_copper_brick = true
			waxed_copper_brick = true
			waxed_exposed_copper_brick = true
			waxed_weathered_copper_brick = true
			waxed_oxidized_copper_brick = true

		[types.cut_block_type.buzzier_bees]
			honeycomb_brick = true
			honeycomb_tile = true

		[types.cut_block_type.atmospheric]
			rosewood = true
			morado = true
			ivory_travertine = true
			peach_travertine = true
			persimmon_travertine = true
			saffron_travertine = true
			dolerite = true
			polished_dolerite = true
			arid_sandstone = true
			smooth_arid_sandstone = true
			cut_arid_sandstone = true
			red_arid_sandstone = true
			smooth_red_arid_sandstone = true
			cut_red_arid_sandstone = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true
			carmine_shingle = true
			carmine_pavement = true

		[types.cut_block_type.quark]
			ancient_planks = true
			azalea_planks = true
			blossom_planks = true
			duskbound_block = true
			iron_plate = true
			rusty_iron_plate = true
			midori_block = true
			blue_nether_bricks = true
			sandstone_bricks = true
			red_sandstone_bricks = true
			soul_sandstone_bricks = true
			cobblestone_bricks = true
			mossy_cobblestone_bricks = true
			blackstone_bricks = true
			dirt_bricks = true
			netherrack_bricks = true
			limestone = true
			polished_limestone = true
			jasper = true
			polished_jasper = true
			shale = true
			polished_shale = true
			myalite = true
			polished_myalite = true
			permafrost = true
			permafrost_bricks = true
			raw_iron_bricks = true
			raw_gold_bricks = true
			raw_copper_bricks = true
			shingles = true
			white_shingles = true
			orange_shingles = true
			magenta_shingles = true
			light_blue_shingles = true
			yellow_shingles = true
			lime_shingles = true
			pink_shingles = true
			gray_shingles = true
			light_gray_shingles = true
			cyan_shingles = true
			purple_shingles = true
			blue_shingles = true
			brown_shingles = true
			green_shingles = true
			red_shingles = true
			black_shingles = true
			soul_sandstone = true
			cut_soul_sandstone = true
			smooth_soul_sandstone = true
			thatch = true
			calcite = true
			polished_calcite = true
			dripstone_block = true
			polished_dripstone = true
			tuff = true
			polished_tuff = true
			granite_bricks = true
			diorite_bricks = true
			andesite_bricks = true
			calcite_bricks = true
			dripstone_bricks = true
			tuff_bricks = true
			limestone_bricks = true
			jasper_bricks = true
			shale_bricks = true
			myalite_bricks = true

		[types.cut_block_type.supplementaries]
			fine_wood = true
			lapis_bricks = true
			ash_bricks = true
			stone_tile = true
			blackstone_tile = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.refurbished_furniture]
			cutting_board = true
			drawer = true
			storage_cabinet = true
			table = true
			mail_box = true
			dark_ceiling_fan = true
			kitchen_sink = true
			toilet = true
			storage_jar = true
			lattice_fence = true
			basin = true
			kitchen_drawer = true
			lattice_fence_gate = true
			kitchen_cabinetry = true
			bath = true
			crate = true
			desk = true
			chair = true
			light_ceiling_fan = true
			kitchen_storage_cabinet = true

		[entries.wood_type.woodworks]
			trapped_chest = true
			boards = true
			chest = true
			beehive = true
			bookshelf = true
			chiseled_bookshelf = true
			ladder = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			vertical_slab = true

		[entries.wood_type.sob]
			counter = true

		[entries.wood_type.storagedrawers]
			trim = true
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			half_drawers_2 = true
			full_drawers_1 = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.woodworks]
			leaf_pile = true

		[entries.leaves_type.refurbished_furniture]
			hedge = true

